### PR TITLE
Use https instead of git URLs for submodules.

### PR DESCRIPTION
**Pull request by mariuspod**
This simplifies dockerized builds with git submodules as needed in this PR:
https://github.com/wmitsuda/erigon/pull/1

### CODE REVIEW

**Comment by androolloyd** [comment]
yes this is a must for my package to build as well,

**Comment by wmitsuda** [comment]
Out of curiosity, why do you guys prefer https? Does it have something to do with certain network restrictions were you work?

**Comment by androolloyd** [comment]
no its because there are no ssh keys to pull content in the build envs.

**Comment by mariuspod** [comment]
That was the easiest solution to the problem where no SSH keys are available inside the docker image when building it. AFAIK git requires you to have SSH keys to clone from `git://` URLs and I thought that's a bit overkill to generate SSH keys into the docker image just to achieve a checkout. Maybe there's an option in git to be less strict on that however which I'm not aware of. Using `https://` based cloning doesn't require SSH keys but just requires host key verification which is fine.

**Comment by wmitsuda** [comment]
It makes sense, thanks for the explanation!

**Pull request merged**
